### ISSUE TITLE
jf_ disco in salesforce 

### ISSUE THREAD

**Issue by ortenau** [tuxfre/esko-SC-scripts#20]
# Esko SC Script issue

## Affected script
* Name: jan
* Version: 

## OS
* Name: mac osx 
* Version: 10.11.6
* Language: german

## Browser
* Name: firefox 
* version: 50.0.2
* language (if different from OS): german

## Short summary if your issue
if you move with your mouse curser over the send screenshot you see a disco ;)
the screenshot pops up and hide 

## Steps to reproduce the issue
go in a job and move over the screenshot

## Other details:
**Don't hesitate to include details and screenshots.**
it is also not possible to save or delete the screenshot, because the disco of screenshot is on top ;)
[salesforce.zip](https://github.com/tuxfre/esko-SC-scripts/files/858457/salesforce.zip)

____
@tuxfre

**Comment by tuxfre** [comment]
Converted the file to an animated GIF (https://cloudconvert.com/mov-to-gif)

![salesforce 1](https://cloud.githubusercontent.com/assets/600530/24155191/69cace3a-0e53-11e7-8984-de741010d838.gif)

**Comment by tuxfre** [comment]
Hi @ortenau 

I'm afraid that there's not much I can do here, your screen isn't wide enough :rofl: 
Ask IT for a bigger monitor.
Do you know what is your current screen resolution on this monitor?

Let me explain, when you hover the link, it triggers the popup, which appears where your pointer is, thus it no longer hovers the link (but the popup) which triggers hiding the popup... and then your cursor is back hovering the link (and it goes on, and on, and on...)

By default, the popup window should have a width equal to 50% of the center column of ServiceCloud (including the "blue" column where the file list is), but if the center column is very small that could cause what you see.
I'll try preventing it from using this blue column as well if I can.

**Comment by tuxfre** [comment]
@ortenau 

I've just pushed a new version (https://github.com/tuxfre/esko-SC-scripts/commit/15acd8cc7869db2eba17622c076d24f209ebba93, yet untested) let me know if this helps ;)

**Comment by tuxfre** [comment]
woops didn't want to close

**Comment by tuxfre** [comment]
Hi @ortenau 

Did the new releases help?

**Comment by ortenau** [comment]
no, sorry,

still the same issue.
I think it has to do with the size of the screenshot.
smaller images works fine.



Bei weiteren Fragen, stehen wir Ihnen gerne zur Verfügung.


Mit freundlichen Grüßen


Jan Fässler




Jan Fässler  |  Senior Solution Support Engineer  |  Esko

Für Support besuchen Sie: http://esko.com/support


[unknown.png]


Esko-Graphics GmbH  -  Heerskamp 6  -  25524 Itzehoe  -  Germany

Geschäftsführer: Holger Jacobsen, Dagmar Reimers, Bruno Vaes
Amtsgericht Itzehoe HRB 2184, Sitz der Gesellschaft: Itzehoe

**Comment by tuxfre** [comment]
Hi @ortenau 

Yes, more or less that's the root of the issue, we don't have enough width...
But what is strange is that it shouldn't span over the links...

Could you give me the screen resolution you use, and also if your browser window spans the whole screen width...

**Comment by ortenau** [comment]
Hi,

I use a third-part tool to merge two monitor in one.
Matrox Powerdesk

[cid:3114DA41-63DB-4351-8D12-FF1E19B9FE33]


Bei weiteren Fragen, stehen wir Ihnen gerne zur Verfügung.


Mit freundlichen Grüßen


Jan Fässler




Jan Fässler  |  Senior Solution Support Engineer  |  Esko

Für Support besuchen Sie: http://esko.com/support


[unknown.png]


Esko-Graphics GmbH  -  Heerskamp 6  -  25524 Itzehoe  -  Germany

Geschäftsführer: Holger Jacobsen, Dagmar Reimers, Bruno Vaes
Amtsgericht Itzehoe HRB 2184, Sitz der Gesellschaft: Itzehoe

**Comment by tuxfre** [comment]
Ah ok...

try going to http://whatsmy.browsersize.com/ so we have some idea on how big it is...

**Comment by ortenau** [comment]
[cid:2ACD37FA-7D11-4AB1-A1DD-1AC2BBD9E4A8]

Bei weiteren Fragen, stehen wir Ihnen gerne zur Verfügung.


Mit freundlichen Grüßen


Jan Fässler




Jan Fässler  |  Senior Solution Support Engineer  |  Esko

Für Support besuchen Sie: http://esko.com/support


[unknown.png]


Esko-Graphics GmbH  -  Heerskamp 6  -  25524 Itzehoe  -  Germany

Geschäftsführer: Holger Jacobsen, Dagmar Reimers, Bruno Vaes
Amtsgericht Itzehoe HRB 2184, Sitz der Gesellschaft: Itzehoe

**Comment by tuxfre** [comment]
Hi @ortenau 

Unfortunately when you answer by mail the images aren't posted to github...

Can you post to https://github.com/tuxfre/esko-SC-scripts/issues/20 ?

**Comment by ortenau** [comment]
![bildschirmfoto 2017-03-23 um 10 00 51](https://cloud.githubusercontent.com/assets/26575100/24240287/46e712ca-0fb1-11e7-8af0-d9934031e31c.png)
![bildschirmfoto 2017-03-23 um 09 51 17](https://cloud.githubusercontent.com/assets/26575100/24240288/46eaf502-0fb1-11e7-95f7-718442476783.png)

**Comment by tuxfre** [comment]
mmm...
So basically the browser window is in a very wide screen... and it has (roughly) a 1:2 ratio
I'd have to see how I can simulate this and figure a workaround for such a special case

I'lll think of it today, and see if I can come up with something


Thanks for the details

**Comment by tuxfre** [comment]
I'm closing as "can't reproduce"... sorry
